import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Bot,
  Boxes,
  Check,
  CircleAlert,
  CircleCheck,
  Clock3,
  Database,
  FileClock,
  GitBranch,
  GitPullRequestArrow,
  Home,
  ListTodo,
  LogOut,
  Menu,
  Network,
  Play,
  RefreshCw,
  Search,
  ShieldCheck,
  Sparkles,
  UserCheck,
  UsersRound,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  activity: Activity,
  approvals: UserCheck,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bot: Bot,
  cases: Boxes,
  check: Check,
  database: Database,
  failed: XCircle,
  graph: Network,
  history: FileClock,
  home: Home,
  logout: LogOut,
  menu: Menu,
  merge: GitPullRequestArrow,
  play: Play,
  refresh: RefreshCw,
  repository: GitBranch,
  search: Search,
  shield: ShieldCheck,
  sparkles: Sparkles,
  teams: UsersRound,
  waiting: Clock3,
  warning: CircleAlert,
  verified: CircleCheck,
  work: ListTodo,
  close: X,
} satisfies Record<string, LucideIcon>;
